### ISSUE TITLE
구현할 함수

### ISSUE THREAD

**Issue by 22100451Yejin** [2022OSST22/No3#4]
어떤 기능을 하는 함수를 설계할지 작성해주세요

**Comment by eunseoryu** [comment]
메뉴 보기
메뉴 추가
메뉴 수정
이 3가지 제안합니다.

**Comment by 22100451Yejin** [comment]
메뉴 삭제 
메뉴 선택
메뉴 저장, 불러오기 
기능도 추가하면 좋을 것 같아요

**Comment by 22100451Yejin** [comment]
메뉴 조회에서 어떤 항목들을 불러올 수 있게 설계할까요?

**Comment by eunseoryu** [comment]
메뉴 조회에서는 이름, 가격, 설명을 볼 수 있도록 설계하는걸로 하면 좋을것같아요

**Comment by eunseoryu** [comment]
여기에다 디저트류, 음료, 등 종류를 구분할 수 있게 종류도 추가하면 될것같습니다.

**Comment by 22100451Yejin** [comment]
그러면 메뉴 이름, 가격, 종류로 검색하는 기능 추가해요!

**Comment by eunseoryu** [comment]
메뉴 보기
메뉴 추가- 종류, 이름 , 가격, 설명
메뉴 수정
메뉴 삭제
메뉴 선택
메뉴 저장, 
불러오기
메뉴 이름, 가격, 종류로 검색

**Comment by eunseoryu** [comment]
그럼 저는 메뉴 저장부터 끝까지 기능 구현하도록 하겠습니다!
