### ISSUE TITLE
함수 구현 관련

### ISSUE THREAD

**Issue by eunseoryu** [2022OSST22/No3#9]
함수 구현에 관해 문제가 생기면 여기서 이야기를 나누어봅시다.

**Comment by 22100451Yejin** [comment]
설계한 Mini project에서 검색 기능, 파일 저장, 로딩 기능을 제외한 모든 함수를 팀원끼리 적절히 분배하여 구현 및 테스트합니다. 추가, 수정, 삭제 기능을 완성할 때마다 git으로 버전 관리하며 개발하도록 합니다.

저희 이번 과제가 이렇게 진행되는데 저희가 나눴던대로 진행하게되면 이번에 구현해야 하는 함수가 분배 없이 진행이 되는데 괜찮을까요?

**Comment by eunseoryu** [comment]
전부 다 구현할 필요는 없는거네요

**Comment by eunseoryu** [comment]
그럼 남은 기능은 추가, 수정, 삭제 기능인데 이 세가지만 분배해서 하면 되는걸까요

**Comment by 22100451Yejin** [comment]
네네 이번에는 전부 다 할 필요 없이 메뉴 보기
메뉴 추가- 종류, 이름 , 가격, 설명
메뉴 수정
메뉴 삭제
메뉴 선택

이것들만 구현하면 될 것 같아요

**Comment by 22100451Yejin** [comment]
보기 추가 수정 / 삭제 선택 이렇게 나누면 좋을 것 같은데 어떠세요?

**Comment by eunseoryu** [comment]
그럼 이 중에 각자 두개씩 맡아서 구현하는걸로 할까요? 혹시 먼저 선택하고싶은 구현 함수 있으신가요?

**Comment by 22100451Yejin** [comment]
제가 보기 추가 수정할게요!

**Comment by 22100451Yejin** [comment]
죄송해요 잘못 눌러서 ㅠㅅㅠ

**Comment by eunseoryu** [comment]
아니에요 괜찮아요. 그럼 제가 나머지 파트 담당하도록 하겠습니다.

**Comment by 22100451Yejin** [comment]
저희 메뉴 보기 말고 물품을 출력하는 함수도 해야 해요

**Comment by eunseoryu** [comment]
dessert.c->구현한 함수, order.c ->main 파일, 헤더파일 수정, makefile 추가 및 PR 했습니다! 확인해주세요

**Comment by eunseoryu** [comment]
그리고 옵션 출력 함수도 함께 구현했습니다.

**Comment by 22100451Yejin** [comment]
저희 이번 과제는 메뉴 저장/ 불러오기/ 메뉴 이름, 가격, 종류로 검색 을 구현해야 하는데 어떻게 나눌까요 ?

**Comment by eunseoryu** [comment]
메뉴  저장과 저번에 제가 구현했던 메뉴 주문이 비슷해서, 이번에 제가 저장과 불러오기를 하면 좋을 것 같아요, 다른 의견도 좋아요!

**Comment by 22100451Yejin** [comment]
그러면 제가 검색 종류 하겠습니다!

**Comment by eunseoryu** [comment]
넵 그럼 이렇게 구현하는걸로 하고, 구현 후 다시 연락드리겠습니다!

**Comment by eunseoryu** [comment]
구현 후 pr 했습니다.확인해주세요!

**Comment by 22100451Yejin** [comment]
확인해서 추가했습니다! 저도 해당 함수들 구현 해서 추가하였고 수정할 부분들 수정하였습니다

**Comment by eunseoryu** [comment]
감사합니다 수고하셨습니다!
